package vista;

import controlador.DespachoController;
import controlador.PedidoController;
import modelo.RutaDistribucion;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import java.util.List;

/**
 *
 * @author Jheim
 */
public class FrmDespacho extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmDespacho.class.getName());

    private final DespachoController controller = new DespachoController();
    private final PedidoController pedidoController = new PedidoController();

    private int idDespachoSeleccionado = 0;

    /**
     * Creates new form FrmDespacho
     */
    public FrmDespacho() {
        initComponents();
        aplicarEstilo();
        cargarPedidos();
        cargarRutas();
        listarDespachos();
        setLocationRelativeTo(null);
    }

    private void aplicarEstilo() {
        java.awt.Color teal = new java.awt.Color(0, 121, 107);
        java.awt.Color fondo = new java.awt.Color(224, 242, 241);

        getContentPane().setBackground(fondo);
        jScrollPane1.getViewport().setBackground(java.awt.Color.WHITE);
        jLabel1.setForeground(teal);

        for (javax.swing.JButton b : new javax.swing.JButton[]{btnGuardarRuta, btnGuardarDespacho, btnActualizarEstado, btnEliminarDespacho}) {
            b.setBackground(teal);
            b.setForeground(java.awt.Color.WHITE);
            b.setFocusPainted(false);
        }

        tblDespachos.getTableHeader().setBackground(teal);
        tblDespachos.getTableHeader().setForeground(java.awt.Color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblOrigen = new javax.swing.JLabel();
        txtOrigen = new javax.swing.JTextField();
        lblDestino = new javax.swing.JLabel();
        txtDestino = new javax.swing.JTextField();
        lblDistancia = new javax.swing.JLabel();
        txtDistancia = new javax.swing.JTextField();
        btnGuardarRuta = new javax.swing.JButton();
        lblPedido = new javax.swing.JLabel();
        cbPedido = new javax.swing.JComboBox<>();
        lblRuta = new javax.swing.JLabel();
        cbRuta = new javax.swing.JComboBox<>();
        lblEstadoDespacho = new javax.swing.JLabel();
        cbEstadoDespacho = new javax.swing.JComboBox<>();
        lblTransportista = new javax.swing.JLabel();
        txtTransportista = new javax.swing.JTextField();
        btnGuardarDespacho = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDespachos = new javax.swing.JTable();
        lblNuevoEstado = new javax.swing.JLabel();
        cbNuevoEstado = new javax.swing.JComboBox<>();
        btnActualizarEstado = new javax.swing.JButton();
        btnEliminarDespacho = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("GESTIÓN DE DESPACHOS");

        lblOrigen.setText("Origen : ");

        lblDestino.setText("Destino : ");

        lblDistancia.setText("Distancia (km) : ");

        btnGuardarRuta.setText("Guardar Ruta");
        btnGuardarRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarRutaActionPerformed(evt);
            }
        });

        lblPedido.setText("Pedido : ");

        lblRuta.setText("Ruta : ");

        lblEstadoDespacho.setText("Estado : ");

        cbEstadoDespacho.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PENDIENTE", "EN_RUTA", "ENTREGADO", "CANCELADO" }));

        lblTransportista.setText("Transportista : ");

        btnGuardarDespacho.setText("Guardar Despacho");
        btnGuardarDespacho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarDespachoActionPerformed(evt);
            }
        });

        tblDespachos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Pedido", "Ruta", "Estado", "Transportista"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDespachos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDespachosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDespachos);

        lblNuevoEstado.setText("Nuevo Estado : ");

        cbNuevoEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PENDIENTE", "EN_RUTA", "ENTREGADO", "CANCELADO" }));

        btnActualizarEstado.setText("Actualizar Estado");
        btnActualizarEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarEstadoActionPerformed(evt);
            }
        });

        btnEliminarDespacho.setText("Eliminar Despacho");
        btnEliminarDespacho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarDespachoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1))
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblOrigen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(lblDestino)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(lblDistancia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDistancia, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(btnGuardarRuta))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPedido)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblRuta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblEstadoDespacho)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbEstadoDespacho, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTransportista)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTransportista, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(btnGuardarDespacho)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblNuevoEstado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbNuevoEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btnActualizarEstado)
                .addGap(20, 20, 20)
                .addComponent(btnEliminarDespacho)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOrigen)
                    .addComponent(txtOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDestino)
                    .addComponent(txtDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDistancia)
                    .addComponent(txtDistancia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardarRuta))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPedido)
                    .addComponent(cbPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRuta)
                    .addComponent(cbRuta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEstadoDespacho)
                    .addComponent(cbEstadoDespacho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTransportista)
                    .addComponent(txtTransportista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardarDespacho))
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNuevoEstado)
                    .addComponent(cbNuevoEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnActualizarEstado)
                    .addComponent(btnEliminarDespacho))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarRutaActionPerformed

        String origen = txtOrigen.getText().trim();
        String destino = txtDestino.getText().trim();

        if (origen.isEmpty() || destino.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Complete origen y destino.");
            return;
        }

        double distancia;
        try {
            distancia = Double.parseDouble(txtDistancia.getText().trim());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Ingrese una distancia válida.");
            return;
        }

        boolean respuesta = controller.guardarRuta(origen, destino, distancia);

        if (respuesta) {
            JOptionPane.showMessageDialog(this, "Ruta registrada correctamente.");
            txtOrigen.setText("");
            txtDestino.setText("");
            txtDistancia.setText("");
            cargarRutas();
        } else {
            JOptionPane.showMessageDialog(this, "Error al registrar la ruta.");
        }

    }//GEN-LAST:event_btnGuardarRutaActionPerformed

    private void btnGuardarDespachoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarDespachoActionPerformed

        if (cbPedido.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "No hay pedidos disponibles. Registre un pedido primero.");
            return;
        }

        if (cbRuta.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "No hay rutas disponibles. Registre una ruta primero.");
            return;
        }

        String transportista = txtTransportista.getText().trim();
        if (transportista.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese el nombre del transportista.");
            return;
        }

        int idPedido;
        int idRuta;
        try {
            idPedido = Integer.parseInt(((String) cbPedido.getSelectedItem()).split(" - ")[0].trim());
            idRuta = Integer.parseInt(((String) cbRuta.getSelectedItem()).split(" - ")[0].trim());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Pedido o ruta inválidos.");
            return;
        }

        String estado = (String) cbEstadoDespacho.getSelectedItem();

        boolean respuesta = controller.guardarDespacho(estado, transportista, idPedido, idRuta);

        if (respuesta) {
            JOptionPane.showMessageDialog(this, "Despacho registrado correctamente.");
            txtTransportista.setText("");
            listarDespachos();
        } else {
            JOptionPane.showMessageDialog(this, "Error al registrar el despacho.");
        }

    }//GEN-LAST:event_btnGuardarDespachoActionPerformed

    private void btnActualizarEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarEstadoActionPerformed

        if (idDespachoSeleccionado == 0) {
            JOptionPane.showMessageDialog(this, "Seleccione un despacho de la tabla.");
            return;
        }

        String nuevoEstado = (String) cbNuevoEstado.getSelectedItem();

        boolean respuesta = controller.actualizarEstadoDespacho(idDespachoSeleccionado, nuevoEstado);

        if (respuesta) {
            JOptionPane.showMessageDialog(this, "Estado actualizado correctamente.");
            listarDespachos();
        } else {
            JOptionPane.showMessageDialog(this, "Error al actualizar el estado.");
        }

    }//GEN-LAST:event_btnActualizarEstadoActionPerformed

    private void btnEliminarDespachoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarDespachoActionPerformed

        if (idDespachoSeleccionado == 0) {
            JOptionPane.showMessageDialog(this, "Seleccione un despacho de la tabla.");
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this,
                "¿Está seguro de eliminar este despacho?", "Confirmar",
                JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            boolean respuesta = controller.eliminarDespacho(idDespachoSeleccionado);

            if (respuesta) {
                JOptionPane.showMessageDialog(this, "Despacho eliminado correctamente.");
                idDespachoSeleccionado = 0;
                listarDespachos();
            } else {
                JOptionPane.showMessageDialog(this, "Error al eliminar el despacho.");
            }
        }

    }//GEN-LAST:event_btnEliminarDespachoActionPerformed

    private void tblDespachosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDespachosMouseClicked

        int fila = tblDespachos.getSelectedRow();

        if (fila != -1) {
            idDespachoSeleccionado = (int) tblDespachos.getValueAt(fila, 0);
        }

    }//GEN-LAST:event_tblDespachosMouseClicked

    private void cargarPedidos() {
        cbPedido.removeAllItems();
        List<Object[]> lista = pedidoController.listarPedidos();
        for (Object[] fila : lista) {
            // fila = {idPedido, nombreCliente, fecha, estado, monto}
            cbPedido.addItem(fila[0] + " - " + fila[1] + " - " + fila[2]);
        }
    }

    private void cargarRutas() {
        cbRuta.removeAllItems();
        List<RutaDistribucion> lista = controller.listarRutas();
        for (RutaDistribucion r : lista) {
            cbRuta.addItem(r.getIdRuta() + " - " + r.getOrigen() + " -> " + r.getDestino());
        }
    }

    private void listarDespachos() {
        DefaultTableModel modelo = (DefaultTableModel) tblDespachos.getModel();
        modelo.setRowCount(0);

        List<Object[]> lista = controller.listarDespachos();
        for (Object[] fila : lista) {
            modelo.addRow(fila);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> new FrmDespacho().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarEstado;
    private javax.swing.JButton btnEliminarDespacho;
    private javax.swing.JButton btnGuardarDespacho;
    private javax.swing.JButton btnGuardarRuta;
    private javax.swing.JComboBox<String> cbEstadoDespacho;
    private javax.swing.JComboBox<String> cbNuevoEstado;
    private javax.swing.JComboBox<String> cbPedido;
    private javax.swing.JComboBox<String> cbRuta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDestino;
    private javax.swing.JLabel lblDistancia;
    private javax.swing.JLabel lblEstadoDespacho;
    private javax.swing.JLabel lblNuevoEstado;
    private javax.swing.JLabel lblOrigen;
    private javax.swing.JLabel lblPedido;
    private javax.swing.JLabel lblRuta;
    private javax.swing.JLabel lblTransportista;
    private javax.swing.JTable tblDespachos;
    private javax.swing.JTextField txtDestino;
    private javax.swing.JTextField txtDistancia;
    private javax.swing.JTextField txtOrigen;
    private javax.swing.JTextField txtTransportista;
    // End of variables declaration//GEN-END:variables
}
