package vista;

import controlador.EntregaController;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import java.sql.Timestamp;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;

/**
 *
 * @author Jheim
 */
public class FrmEntrega extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmEntrega.class.getName());

    private final EntregaController controller = new EntregaController();

    private int idEntregaSeleccionada = 0;

    private static final DateTimeFormatter FORMATO_FECHA = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");

    /**
     * Creates new form FrmEntrega
     */
    public FrmEntrega() {
        initComponents();
        aplicarEstilo();
        cargarDespachos();
        listarEntregas();
        actualizarFechaActual();
        setLocationRelativeTo(null);
    }

    private void aplicarEstilo() {
        java.awt.Color azul = new java.awt.Color(21, 101, 192);
        java.awt.Color fondo = new java.awt.Color(227, 238, 250);

        getContentPane().setBackground(fondo);
        jScrollPane1.getViewport().setBackground(java.awt.Color.WHITE);
        jLabel1.setForeground(azul);

        for (javax.swing.JButton b : new javax.swing.JButton[]{btnGuardarEntrega, btnEliminarEntrega}) {
            b.setBackground(azul);
            b.setForeground(java.awt.Color.WHITE);
            b.setFocusPainted(false);
        }

        tblEntregas.getTableHeader().setBackground(azul);
        tblEntregas.getTableHeader().setForeground(java.awt.Color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblDespacho = new javax.swing.JLabel();
        cbDespacho = new javax.swing.JComboBox<>();
        lblFechaEntrega = new javax.swing.JLabel();
        txtFechaEntrega = new javax.swing.JTextField();
        btnGuardarEntrega = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEntregas = new javax.swing.JTable();
        btnEliminarEntrega = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("GESTIÓN DE ENTREGAS");

        lblDespacho.setText("Despacho : ");

        lblFechaEntrega.setText("Fecha Entrega (yyyy-MM-dd HH:mm:ss) : ");

        btnGuardarEntrega.setText("Guardar Entrega");
        btnGuardarEntrega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarEntregaActionPerformed(evt);
            }
        });

        tblEntregas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Despacho", "Pedido", "Estado", "Transportista", "Fecha Entrega"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblEntregas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEntregasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblEntregas);

        btnEliminarEntrega.setText("Eliminar Entrega");
        btnEliminarEntrega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarEntregaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1))
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblDespacho)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbDespacho, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblFechaEntrega)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFechaEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btnGuardarEntrega)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(btnEliminarEntrega)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDespacho)
                    .addComponent(cbDespacho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFechaEntrega)
                    .addComponent(txtFechaEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardarEntrega))
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(btnEliminarEntrega)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarEntregaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarEntregaActionPerformed

        if (cbDespacho.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "No hay despachos disponibles para registrar entrega.");
            return;
        }

        int idDespacho;
        try {
            idDespacho = Integer.parseInt(((String) cbDespacho.getSelectedItem()).split(" - ")[0].trim());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Despacho inválido.");
            return;
        }

        Timestamp fecha;
        try {
            LocalDateTime ldt = LocalDateTime.parse(txtFechaEntrega.getText().trim(), FORMATO_FECHA);
            fecha = Timestamp.valueOf(ldt);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Formato de fecha inválido. Use yyyy-MM-dd HH:mm:ss.");
            return;
        }

        boolean respuesta = controller.guardarEntrega(fecha, idDespacho);

        if (respuesta) {
            JOptionPane.showMessageDialog(this, "Entrega registrada correctamente.");
            cargarDespachos();
            listarEntregas();
            actualizarFechaActual();
        } else {
            JOptionPane.showMessageDialog(this, "Error al registrar la entrega.");
        }

    }//GEN-LAST:event_btnGuardarEntregaActionPerformed

    private void btnEliminarEntregaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarEntregaActionPerformed

        if (idEntregaSeleccionada == 0) {
            JOptionPane.showMessageDialog(this, "Seleccione una entrega de la tabla.");
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this,
                "¿Está seguro de eliminar esta entrega? También se eliminarán sus incidencias asociadas.", "Confirmar",
                JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            boolean respuesta = controller.eliminarEntrega(idEntregaSeleccionada);

            if (respuesta) {
                JOptionPane.showMessageDialog(this, "Entrega eliminada correctamente.");
                idEntregaSeleccionada = 0;
                cargarDespachos();
                listarEntregas();
            } else {
                JOptionPane.showMessageDialog(this, "Error al eliminar la entrega.");
            }
        }

    }//GEN-LAST:event_btnEliminarEntregaActionPerformed

    private void tblEntregasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEntregasMouseClicked

        int fila = tblEntregas.getSelectedRow();

        if (fila != -1) {
            idEntregaSeleccionada = (int) tblEntregas.getValueAt(fila, 0);
        }

    }//GEN-LAST:event_tblEntregasMouseClicked

    private void cargarDespachos() {
        cbDespacho.removeAllItems();
        List<Object[]> lista = controller.listarDespachosSinEntrega();
        for (Object[] fila : lista) {
            // fila = {idDespacho, fk_idPedido, estado, transportista}
            cbDespacho.addItem(fila[0] + " - Pedido " + fila[1] + " - " + fila[2] + " - " + fila[3]);
        }
    }

    private void listarEntregas() {
        DefaultTableModel modelo = (DefaultTableModel) tblEntregas.getModel();
        modelo.setRowCount(0);

        List<Object[]> lista = controller.listarEntregas();
        for (Object[] fila : lista) {
            modelo.addRow(fila);
        }
    }

    private void actualizarFechaActual() {
        txtFechaEntrega.setText(LocalDateTime.now().format(FORMATO_FECHA));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> new FrmEntrega().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminarEntrega;
    private javax.swing.JButton btnGuardarEntrega;
    private javax.swing.JComboBox<String> cbDespacho;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDespacho;
    private javax.swing.JLabel lblFechaEntrega;
    private javax.swing.JTable tblEntregas;
    private javax.swing.JTextField txtFechaEntrega;
    // End of variables declaration//GEN-END:variables
}
