package vista;

import controlador.EntregaController;
import controlador.IncidenciaController;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import java.util.List;

/**
 *
 * @author Jheim
 */
public class FrmIncidencia extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmIncidencia.class.getName());

    private final IncidenciaController controller = new IncidenciaController();
    private final EntregaController entregaController = new EntregaController();

    private int idIncidenciaSeleccionada = 0;

    /**
     * Creates new form FrmIncidencia
     */
    public FrmIncidencia() {
        initComponents();
        aplicarEstilo();
        cargarEntregas();
        listarIncidencias();
        setLocationRelativeTo(null);
    }

    private void aplicarEstilo() {
        java.awt.Color rojo = new java.awt.Color(191, 54, 12);
        java.awt.Color fondo = new java.awt.Color(253, 233, 227);

        getContentPane().setBackground(fondo);
        jScrollPane1.getViewport().setBackground(java.awt.Color.WHITE);
        jLabel1.setForeground(rojo);

        for (javax.swing.JButton b : new javax.swing.JButton[]{btnGuardarIncidencia, btnEliminarIncidencia}) {
            b.setBackground(rojo);
            b.setForeground(java.awt.Color.WHITE);
            b.setFocusPainted(false);
        }

        tblIncidencias.getTableHeader().setBackground(rojo);
        tblIncidencias.getTableHeader().setForeground(java.awt.Color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblEntrega = new javax.swing.JLabel();
        cbEntrega = new javax.swing.JComboBox<>();
        lblTipo = new javax.swing.JLabel();
        cbTipo = new javax.swing.JComboBox<>();
        lblDescripcion = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        btnGuardarIncidencia = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblIncidencias = new javax.swing.JTable();
        btnEliminarIncidencia = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("GESTIÓN DE INCIDENCIAS");

        lblEntrega.setText("Entrega : ");

        lblTipo.setText("Tipo : ");

        cbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DAÑO", "ERROR_PEDIDO", "RETRASO", "OTRO" }));

        lblDescripcion.setText("Descripción : ");

        btnGuardarIncidencia.setText("Guardar Incidencia");
        btnGuardarIncidencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarIncidenciaActionPerformed(evt);
            }
        });

        tblIncidencias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Entrega", "Fecha Entrega", "Tipo", "Descripción"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblIncidencias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblIncidenciasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblIncidencias);

        btnEliminarIncidencia.setText("Eliminar Incidencia");
        btnEliminarIncidencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarIncidenciaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1))
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblEntrega)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(lblTipo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblDescripcion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btnGuardarIncidencia)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(btnEliminarIncidencia)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEntrega)
                    .addComponent(cbEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTipo)
                    .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDescripcion)
                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardarIncidencia))
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(btnEliminarIncidencia)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarIncidenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarIncidenciaActionPerformed

        if (cbEntrega.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "No hay entregas disponibles. Registre una entrega primero.");
            return;
        }

        String descripcion = txtDescripcion.getText().trim();
        if (descripcion.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese una descripción de la incidencia.");
            return;
        }

        int idEntrega;
        try {
            idEntrega = Integer.parseInt(((String) cbEntrega.getSelectedItem()).split(" - ")[0].trim());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Entrega inválida.");
            return;
        }

        String tipo = (String) cbTipo.getSelectedItem();

        boolean respuesta = controller.guardarIncidencia(tipo, descripcion, idEntrega);

        if (respuesta) {
            JOptionPane.showMessageDialog(this, "Incidencia registrada correctamente.");
            txtDescripcion.setText("");
            listarIncidencias();
        } else {
            JOptionPane.showMessageDialog(this, "Error al registrar la incidencia.");
        }

    }//GEN-LAST:event_btnGuardarIncidenciaActionPerformed

    private void btnEliminarIncidenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarIncidenciaActionPerformed

        if (idIncidenciaSeleccionada == 0) {
            JOptionPane.showMessageDialog(this, "Seleccione una incidencia de la tabla.");
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this,
                "¿Está seguro de eliminar esta incidencia?", "Confirmar",
                JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            boolean respuesta = controller.eliminarIncidencia(idIncidenciaSeleccionada);

            if (respuesta) {
                JOptionPane.showMessageDialog(this, "Incidencia eliminada correctamente.");
                idIncidenciaSeleccionada = 0;
                listarIncidencias();
            } else {
                JOptionPane.showMessageDialog(this, "Error al eliminar la incidencia.");
            }
        }

    }//GEN-LAST:event_btnEliminarIncidenciaActionPerformed

    private void tblIncidenciasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblIncidenciasMouseClicked

        int fila = tblIncidencias.getSelectedRow();

        if (fila != -1) {
            idIncidenciaSeleccionada = (int) tblIncidencias.getValueAt(fila, 0);
        }

    }//GEN-LAST:event_tblIncidenciasMouseClicked

    private void cargarEntregas() {
        cbEntrega.removeAllItems();
        List<Object[]> lista = entregaController.listarEntregas();
        for (Object[] fila : lista) {
            // fila = {idEntrega, fk_idDespacho, fk_idPedido, estado, transportista, fechaEntrega}
            cbEntrega.addItem(fila[0] + " - Pedido " + fila[2] + " - " + fila[5]);
        }
    }

    private void listarIncidencias() {
        DefaultTableModel modelo = (DefaultTableModel) tblIncidencias.getModel();
        modelo.setRowCount(0);

        List<Object[]> lista = controller.listarIncidencias();
        for (Object[] fila : lista) {
            modelo.addRow(fila);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> new FrmIncidencia().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminarIncidencia;
    private javax.swing.JButton btnGuardarIncidencia;
    private javax.swing.JComboBox<String> cbEntrega;
    private javax.swing.JComboBox<String> cbTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblEntrega;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JTable tblIncidencias;
    private javax.swing.JTextField txtDescripcion;
    // End of variables declaration//GEN-END:variables
}
