package vista;

import controlador.ClienteController;
import controlador.InventarioController;
import controlador.PedidoController;
import controlador.ProductoController;
import modelo.Cliente;
import modelo.DetallePedido;
import modelo.Producto;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import java.sql.Date;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Jheim
 */
public class FrmPedido extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmPedido.class.getName());

    private final PedidoController controller = new PedidoController();
    private final ClienteController clienteController = new ClienteController();
    private final ProductoController productoController = new ProductoController();
    private final InventarioController inventarioController = new InventarioController();

    private List<Producto> productos = new ArrayList<>();
    private List<DetallePedido> lineasPendientes = new ArrayList<>();

    private int idPedidoSeleccionado = 0;

    /**
     * Creates new form FrmPedido
     */
    public FrmPedido() {
        initComponents();
        aplicarEstilo();
        cargarClientes();
        cargarProductos();
        listarPedidos();
        setLocationRelativeTo(null);
    }

    private void aplicarEstilo() {
        java.awt.Color morado = new java.awt.Color(94, 53, 145);
        java.awt.Color fondo = new java.awt.Color(240, 235, 247);

        getContentPane().setBackground(fondo);
        jScrollPane1.getViewport().setBackground(java.awt.Color.WHITE);
        jScrollPane2.getViewport().setBackground(java.awt.Color.WHITE);
        jLabel1.setForeground(morado);

        for (javax.swing.JButton b : new javax.swing.JButton[]{btnAgregarLinea, btnGuardarPedido, btnLimpiar, btnVerDetalle, btnEliminarPedido}) {
            b.setBackground(morado);
            b.setForeground(java.awt.Color.WHITE);
            b.setFocusPainted(false);
        }

        tblDetalleNuevo.getTableHeader().setBackground(morado);
        tblDetalleNuevo.getTableHeader().setForeground(java.awt.Color.WHITE);
        tblPedidos.getTableHeader().setBackground(morado);
        tblPedidos.getTableHeader().setForeground(java.awt.Color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblCliente = new javax.swing.JLabel();
        cbCliente = new javax.swing.JComboBox<>();
        lblFecha = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        lblEstado = new javax.swing.JLabel();
        cbEstado = new javax.swing.JComboBox<>();
        lblProducto = new javax.swing.JLabel();
        cbProducto = new javax.swing.JComboBox<>();
        lblCantidad = new javax.swing.JLabel();
        txtCantidadLinea = new javax.swing.JTextField();
        btnAgregarLinea = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDetalleNuevo = new javax.swing.JTable();
        lblMontoTotal = new javax.swing.JLabel();
        btnGuardarPedido = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPedidos = new javax.swing.JTable();
        btnVerDetalle = new javax.swing.JButton();
        btnEliminarPedido = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("GESTIÓN DE PEDIDOS");

        lblCliente.setText("Cliente : ");

        lblFecha.setText("Fecha (yyyy-MM-dd) : ");

        txtFecha.setText(LocalDate.now().toString());

        lblEstado.setText("Estado : ");

        cbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PENDIENTE", "EN_PROCESO", "ENTREGADO", "CANCELADO" }));

        lblProducto.setText("Producto : ");

        lblCantidad.setText("Cantidad : ");

        btnAgregarLinea.setText("Agregar Línea");
        btnAgregarLinea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarLineaActionPerformed(evt);
            }
        });

        tblDetalleNuevo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Producto", "Cantidad", "Precio Unit.", "Subtotal"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblDetalleNuevo);

        lblMontoTotal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMontoTotal.setText("Monto total: S/ 0.00");

        btnGuardarPedido.setText("Guardar Pedido");
        btnGuardarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarPedidoActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        tblPedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Cliente", "Fecha", "Estado", "Monto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPedidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPedidosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblPedidos);

        btnVerDetalle.setText("Ver Detalle");
        btnVerDetalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerDetalleActionPerformed(evt);
            }
        });

        btnEliminarPedido.setText("Eliminar Pedido");
        btnEliminarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarPedidoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1))
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblFecha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblEstado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblProducto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCantidad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCantidadLinea, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(btnAgregarLinea)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblMontoTotal)
                .addGap(30, 30, 30)
                .addComponent(btnGuardarPedido)
                .addGap(20, 20, 20)
                .addComponent(btnLimpiar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(btnVerDetalle)
                .addGap(20, 20, 20)
                .addComponent(btnEliminarPedido)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCliente)
                    .addComponent(cbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFecha)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEstado)
                    .addComponent(cbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProducto)
                    .addComponent(cbProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCantidad)
                    .addComponent(txtCantidadLinea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregarLinea))
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMontoTotal)
                    .addComponent(btnGuardarPedido)
                    .addComponent(btnLimpiar))
                .addGap(20, 20, 20)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVerDetalle)
                    .addComponent(btnEliminarPedido))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarLineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarLineaActionPerformed

        if (cbProducto.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "No hay productos disponibles.");
            return;
        }

        String codProducto = (String) cbProducto.getSelectedItem();

        int cantidad;
        try {
            cantidad = Integer.parseInt(txtCantidadLinea.getText().trim());
            if (cantidad <= 0) {
                JOptionPane.showMessageDialog(this, "La cantidad debe ser mayor a 0.");
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Ingrese una cantidad válida.");
            return;
        }

        double precio = 0;
        String nombreProducto = codProducto;
        for (Producto p : productos) {
            if (p.getCodProducto().equals(codProducto)) {
                precio = p.getPrecio();
                nombreProducto = p.getNombre();
                break;
            }
        }

        int stockDisponible = inventarioController.obtenerStockPorProducto(codProducto);
        int yaEnCarrito = 0;
        for (DetallePedido d : lineasPendientes) {
            if (d.getFkCodProducto().equals(codProducto)) {
                yaEnCarrito += d.getCantidad();
            }
        }

        if (yaEnCarrito + cantidad > stockDisponible) {
            JOptionPane.showMessageDialog(this,
                    "Stock insuficiente para " + nombreProducto + ".\n"
                    + "Disponible: " + stockDisponible + " | En este pedido: " + yaEnCarrito);
            return;
        }

        DetallePedido linea = new DetallePedido(codProducto, cantidad, precio);
        lineasPendientes.add(linea);

        DefaultTableModel modelo = (DefaultTableModel) tblDetalleNuevo.getModel();
        modelo.addRow(new Object[]{nombreProducto, cantidad, precio, linea.getSubtotal()});

        txtCantidadLinea.setText("");
        actualizarMontoTotal();

    }//GEN-LAST:event_btnAgregarLineaActionPerformed

    private void btnGuardarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarPedidoActionPerformed

        if (cbCliente.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Seleccione un cliente.");
            return;
        }

        if (lineasPendientes.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Agregue al menos un producto al pedido.");
            return;
        }

        int idCliente;
        try {
            String seleccion = (String) cbCliente.getSelectedItem();
            idCliente = Integer.parseInt(seleccion.split(" - ")[0].trim());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Cliente inválido.");
            return;
        }

        Date fechaSql;
        try {
            fechaSql = Date.valueOf(txtFecha.getText().trim());
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, "Formato de fecha inválido. Use yyyy-MM-dd.");
            return;
        }

        String estado = (String) cbEstado.getSelectedItem();

        boolean respuesta = controller.guardarPedidoCompleto(idCliente, fechaSql, estado, lineasPendientes);

        if (respuesta) {
            JOptionPane.showMessageDialog(this, "Pedido registrado correctamente.");
            limpiarFormulario();
            listarPedidos();
        } else {
            JOptionPane.showMessageDialog(this, "Error al registrar el pedido.");
        }

    }//GEN-LAST:event_btnGuardarPedidoActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiarFormulario();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnVerDetalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerDetalleActionPerformed

        if (idPedidoSeleccionado == 0) {
            JOptionPane.showMessageDialog(this, "Seleccione un pedido de la tabla.");
            return;
        }

        List<Object[]> detalle = controller.listarDetallePorPedido(idPedidoSeleccionado);

        DefaultTableModel modelo = new DefaultTableModel(new Object[]{"IdDetalle", "Producto", "Cantidad", "Precio Unit."}, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        for (Object[] fila : detalle) {
            modelo.addRow(fila);
        }

        javax.swing.JTable tabla = new javax.swing.JTable(modelo);
        javax.swing.JScrollPane scroll = new javax.swing.JScrollPane(tabla);
        scroll.setPreferredSize(new java.awt.Dimension(500, 200));

        JOptionPane.showMessageDialog(this, scroll, "Detalle del Pedido #" + idPedidoSeleccionado, JOptionPane.PLAIN_MESSAGE);

    }//GEN-LAST:event_btnVerDetalleActionPerformed

    private void btnEliminarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarPedidoActionPerformed

        if (idPedidoSeleccionado == 0) {
            JOptionPane.showMessageDialog(this, "Seleccione un pedido de la tabla.");
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this,
                "¿Está seguro de eliminar este pedido y todas sus líneas?", "Confirmar",
                JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            boolean respuesta = controller.eliminarPedido(idPedidoSeleccionado);

            if (respuesta) {
                JOptionPane.showMessageDialog(this, "Pedido eliminado correctamente.");
                idPedidoSeleccionado = 0;
                listarPedidos();
            } else {
                JOptionPane.showMessageDialog(this, "Error al eliminar el pedido.");
            }
        }

    }//GEN-LAST:event_btnEliminarPedidoActionPerformed

    private void tblPedidosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPedidosMouseClicked

        int fila = tblPedidos.getSelectedRow();

        if (fila != -1) {
            idPedidoSeleccionado = (int) tblPedidos.getValueAt(fila, 0);
        }

    }//GEN-LAST:event_tblPedidosMouseClicked

    private void cargarClientes() {
        cbCliente.removeAllItems();
        List<Cliente> lista = clienteController.listarClientes();
        for (Cliente c : lista) {
            cbCliente.addItem(c.getIdCliente() + " - " + c.getNombre());
        }
    }

    private void cargarProductos() {
        cbProducto.removeAllItems();
        productos = productoController.listarProductos();
        for (Producto p : productos) {
            cbProducto.addItem(p.getCodProducto());
        }
    }

    private void listarPedidos() {
        DefaultTableModel modelo = (DefaultTableModel) tblPedidos.getModel();
        modelo.setRowCount(0);

        List<Object[]> lista = controller.listarPedidos();
        for (Object[] fila : lista) {
            modelo.addRow(fila);
        }
    }

    private void actualizarMontoTotal() {
        double total = 0;
        for (DetallePedido d : lineasPendientes) {
            total += d.getSubtotal();
        }
        lblMontoTotal.setText(String.format("Monto total: S/ %.2f", total));
    }

    private void limpiarFormulario() {
        lineasPendientes.clear();
        ((DefaultTableModel) tblDetalleNuevo.getModel()).setRowCount(0);
        actualizarMontoTotal();
        txtFecha.setText(LocalDate.now().toString());
        txtCantidadLinea.setText("");
        if (cbCliente.getItemCount() > 0) cbCliente.setSelectedIndex(0);
        if (cbEstado.getItemCount() > 0) cbEstado.setSelectedIndex(0);
        if (cbProducto.getItemCount() > 0) cbProducto.setSelectedIndex(0);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> new FrmPedido().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarLinea;
    private javax.swing.JButton btnEliminarPedido;
    private javax.swing.JButton btnGuardarPedido;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnVerDetalle;
    private javax.swing.JComboBox<String> cbCliente;
    private javax.swing.JComboBox<String> cbEstado;
    private javax.swing.JComboBox<String> cbProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblMontoTotal;
    private javax.swing.JLabel lblProducto;
    private javax.swing.JTable tblDetalleNuevo;
    private javax.swing.JTable tblPedidos;
    private javax.swing.JTextField txtCantidadLinea;
    private javax.swing.JTextField txtFecha;
    // End of variables declaration//GEN-END:variables
}
