package vista;

import controlador.PedidoController;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import java.util.List;

/**
 *
 * @author Jheim
 */
public class FrmReporte extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmReporte.class.getName());

    private final PedidoController controller = new PedidoController();

    private List<Object[]> todosLosPedidos;
    private int idPedidoSeleccionado = 0;

    /**
     * Creates new form FrmReporte
     */
    public FrmReporte() {
        initComponents();
        aplicarEstilo();
        cargarReporte();
        setLocationRelativeTo(null);
    }

    private void aplicarEstilo() {
        java.awt.Color gris = new java.awt.Color(55, 71, 79);
        java.awt.Color fondo = new java.awt.Color(236, 239, 241);

        getContentPane().setBackground(fondo);
        jScrollPane1.getViewport().setBackground(java.awt.Color.WHITE);
        jLabel1.setForeground(gris);

        btnFiltrar.setBackground(gris);
        btnFiltrar.setForeground(java.awt.Color.WHITE);
        btnFiltrar.setFocusPainted(false);

        btnEliminarReporte.setBackground(new java.awt.Color(183, 28, 28));
        btnEliminarReporte.setForeground(java.awt.Color.WHITE);
        btnEliminarReporte.setFocusPainted(false);

        tblReporte.getTableHeader().setBackground(gris);
        tblReporte.getTableHeader().setForeground(java.awt.Color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblFiltro = new javax.swing.JLabel();
        cbFiltroEstado = new javax.swing.JComboBox<>();
        btnFiltrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblReporte = new javax.swing.JTable();
        lblTotalPedidos = new javax.swing.JLabel();
        lblMontoTotalReporte = new javax.swing.JLabel();
        btnEliminarReporte = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("REPORTE DE PEDIDOS");

        lblFiltro.setText("Filtrar por Estado : ");

        cbFiltroEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TODOS", "PENDIENTE", "EN_PROCESO", "ENTREGADO", "CANCELADO" }));

        btnFiltrar.setText("Filtrar");
        btnFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarActionPerformed(evt);
            }
        });

        tblReporte.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Cliente", "Fecha", "Estado", "Monto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblReporte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblReporteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblReporte);

        lblTotalPedidos.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblTotalPedidos.setText("Total de pedidos: 0");

        lblMontoTotalReporte.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblMontoTotalReporte.setText("Monto total: S/ 0.00");

        btnEliminarReporte.setText("Eliminar Pedido");
        btnEliminarReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarReporteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1))
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblFiltro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbFiltroEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btnFiltrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblTotalPedidos)
                .addGap(40, 40, 40)
                .addComponent(lblMontoTotalReporte)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(btnEliminarReporte)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFiltro)
                    .addComponent(cbFiltroEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFiltrar))
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalPedidos)
                    .addComponent(lblMontoTotalReporte))
                .addGap(15, 15, 15)
                .addComponent(btnEliminarReporte)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarActionPerformed
        aplicarFiltro();
    }//GEN-LAST:event_btnFiltrarActionPerformed

    private void tblReporteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblReporteMouseClicked

        int fila = tblReporte.getSelectedRow();

        if (fila != -1) {
            idPedidoSeleccionado = (int) tblReporte.getValueAt(fila, 0);
        }

    }//GEN-LAST:event_tblReporteMouseClicked

    private void btnEliminarReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarReporteActionPerformed

        if (idPedidoSeleccionado == 0) {
            JOptionPane.showMessageDialog(this, "Seleccione un pedido de la tabla.");
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this,
                "¿Está seguro de eliminar el pedido #" + idPedidoSeleccionado + " y todas sus líneas?", "Confirmar",
                JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            boolean respuesta = controller.eliminarPedido(idPedidoSeleccionado);

            if (respuesta) {
                JOptionPane.showMessageDialog(this, "Pedido eliminado correctamente.");
                idPedidoSeleccionado = 0;
                cargarReporte();
            } else {
                JOptionPane.showMessageDialog(this, "Error al eliminar el pedido.");
            }
        }

    }//GEN-LAST:event_btnEliminarReporteActionPerformed

    private void cargarReporte() {
        todosLosPedidos = controller.listarPedidos();
        aplicarFiltro();
    }

    private void aplicarFiltro() {

        String filtro = (String) cbFiltroEstado.getSelectedItem();

        DefaultTableModel modelo = (DefaultTableModel) tblReporte.getModel();
        modelo.setRowCount(0);

        int cantidad = 0;
        double montoTotal = 0;

        for (Object[] fila : todosLosPedidos) {
            // fila = {idPedido, nombreCliente, fecha, estado, monto}
            String estado = (String) fila[3];

            if ("TODOS".equals(filtro) || estado.equals(filtro)) {
                modelo.addRow(fila);
                cantidad++;
                montoTotal += (double) fila[4];
            }
        }

        lblTotalPedidos.setText("Total de pedidos: " + cantidad);
        lblMontoTotalReporte.setText(String.format("Monto total: S/ %.2f", montoTotal));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> new FrmReporte().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminarReporte;
    private javax.swing.JButton btnFiltrar;
    private javax.swing.JComboBox<String> cbFiltroEstado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFiltro;
    private javax.swing.JLabel lblMontoTotalReporte;
    private javax.swing.JLabel lblTotalPedidos;
    private javax.swing.JTable tblReporte;
    // End of variables declaration//GEN-END:variables
}
